apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: "cirros-datavol"
spec:
  source:
      http:
         url: "https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img"
  pvc:
    volumeMode: Block
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: "1Gi"
